const statesData = [
  {
    stateName: 'TODO',
  },
  {
    stateName: 'IN_PROGRESS',
  },
  {
    stateName: 'DONE',
  },
];

const taskData = [
  { name: 'Create a new website' },
  { name: 'Implement user authentication' },
  { name: 'Write unit tests for the authentication functionality' },
  { name: 'Set up a CI/CD pipeline' },
  { name: 'Design the homepage layout' },
  { name: 'Optimize database queries' },
  { name: 'Fix navigation bar bugs' },
  { name: 'Research third-party API integrations' },
  { name: 'Update the privacy policy page' },
  { name: 'Improve accessibility features' },
  { name: 'Create a contact form' },
  { name: 'Develop a product listing page' },
  { name: 'Migrate legacy data to the new system' },
  { name: 'Implement a dark mode toggle' },
  { name: 'Set up email notifications' },
  { name: 'Build a custom admin dashboard' },
  { name: 'Write documentation for the API' },
  { name: 'Test mobile responsiveness' },
  { name: 'Design a logo for the project' },
  { name: 'Implement OAuth authentication' },
  { name: 'Add pagination to the blog section' },
  { name: 'Fix broken image links' },
  { name: 'Monitor server performance' },
  { name: 'Refactor backend code for efficiency' },
  { name: 'Create a password reset feature' },
  { name: 'Develop a real-time chat module' },
  { name: 'Add Google Analytics tracking' },
  { name: 'Improve SEO metadata' },
  { name: 'Implement file upload functionality' },
  { name: 'Create a user profile page' },
  { name: 'Implement unit tests for the database layer' },
  { name: 'Design an about-us page' },
  { name: 'Fix footer alignment issues' },
  { name: 'Research scalability solutions' },
  { name: 'Add multi-language support' },
  { name: 'Create a sitemap for the website' },
  { name: 'Set up role-based access control' },
  { name: 'Develop a subscription management system' },
  { name: 'Fix session timeout bugs' },
  { name: 'Optimize page load speed' },
  { name: 'Create a testimonial carousel' },
  { name: 'Implement a search feature' },
  { name: 'Add a product comparison feature' },
  { name: 'Build a responsive image gallery' },
  { name: 'Set up error logging' },
  { name: 'Create a custom 404 error page' },
  { name: 'Update outdated dependencies' },
  { name: 'Develop a FAQ page' },
  { name: 'Add a newsletter subscription form' },
  { name: 'Perform cross-browser testing' },
];

module.exports = { taskData, statesData };
